[package]
name = "chippers"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
pixels = "0.13"
rand = "0.8.5"
winit = { version = "0.30.5", features = ["x11", "rwh_04", "rwh_05"] }
